// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxjhT37K7RsbaStjIaHoSwIK2VC8bidJ0',
    appId: '1:891775838989:web:1b2461c437161fde291e44',
    messagingSenderId: '891775838989',
    projectId: 'caglasurmelihome',
    authDomain: 'caglasurmelihome.firebaseapp.com',
    storageBucket: 'caglasurmelihome.appspot.com',
    measurementId: 'G-7FSBE6DC0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXe5hrEj1kqwL_1cd1FRs6wiDyNHZOJ7A',
    appId: '1:891775838989:android:e973e3b4c63aa44e291e44',
    messagingSenderId: '891775838989',
    projectId: 'caglasurmelihome',
    storageBucket: 'caglasurmelihome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGvI35gyVdJTOiCRgGly3rXpl4j-dz8Hs',
    appId: '1:891775838989:ios:e015618ab063c597291e44',
    messagingSenderId: '891775838989',
    projectId: 'caglasurmelihome',
    storageBucket: 'caglasurmelihome.appspot.com',
    iosClientId: '891775838989-v501oi7brs5fdohtou0j28mc94d6bn9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.envanterKontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGvI35gyVdJTOiCRgGly3rXpl4j-dz8Hs',
    appId: '1:891775838989:ios:e015618ab063c597291e44',
    messagingSenderId: '891775838989',
    projectId: 'caglasurmelihome',
    storageBucket: 'caglasurmelihome.appspot.com',
    iosClientId: '891775838989-v501oi7brs5fdohtou0j28mc94d6bn9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.envanterKontrol',
  );
}
