// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvurWB1vcJhC9YVwlKva-KJ1hql6nbE9U',
    appId: '1:44107571506:web:44bff548c64d0ff6b2772b',
    messagingSenderId: '44107571506',
    projectId: 'cansgomlek',
    authDomain: 'cansgomlek.firebaseapp.com',
    storageBucket: 'cansgomlek.appspot.com',
    measurementId: 'G-K4N3MQWC3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbS_-nKYU4z9QIfqUhzqzeylrfPyK1Ck',
    appId: '1:44107571506:android:1f84b6df934249f0b2772b',
    messagingSenderId: '44107571506',
    projectId: 'cansgomlek',
    storageBucket: 'cansgomlek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8BTEm-UMJ4FDPFzBnPELC-ao3uVgM5A',
    appId: '1:44107571506:ios:0422d69c6204a149b2772b',
    messagingSenderId: '44107571506',
    projectId: 'cansgomlek',
    storageBucket: 'cansgomlek.appspot.com',
    iosClientId: '44107571506-rsgr5caop3kcq6vt3had1c7014l8j0nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.envanterKontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8BTEm-UMJ4FDPFzBnPELC-ao3uVgM5A',
    appId: '1:44107571506:ios:0422d69c6204a149b2772b',
    messagingSenderId: '44107571506',
    projectId: 'cansgomlek',
    storageBucket: 'cansgomlek.appspot.com',
    iosClientId: '44107571506-rsgr5caop3kcq6vt3had1c7014l8j0nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.envanterKontrol',
  );
}
